
%runtime "alaqillabels.swg"    /* Common C API type-checking code */
%runtime "alaqilrun.swg"       /* Common C API type-checking code */
%runtime "alaqilerrors.swg"    /* alaqil errors */   
%runtime "rubyhead.swg"      /* Ruby includes and fixes */   
%runtime "rubyerrors.swg"    /* Ruby errors */   
%runtime "rubytracking.swg"  /* API for tracking C++ classes to Ruby objects */
%runtime "rubyapi.swg"
%runtime "rubyrun.swg"
