#!/bin/bash

# Update alaqil tarball on openSUSE Build Service to contain the latest from master
# Requires the openSUSE Build Service command-line tool (osc)
# See http://openbuildservice.org/download/
# And these packages: obs-service-tar_scm obs-service-recompress obs-service-set_version

# Results appear at https://build.opensuse.org/package/show/home:kwk:alaqil/alaqil-raw

set -e
set -x

rm -rf home-kwk-alaqil/alaqil-raw
mkdir -p home-kwk-alaqil
cd home-kwk-alaqil
# check out 'alaqil-raw'
osc co -o alaqil-raw home:kwk:alaqil alaqil-raw
cd alaqil-raw
# remove existing tarball
osc rm alaqil*tar.bz2
# fetch latest master branch from git and create tarball
osc service disabledrun
# add new tarball
osc addremove
# check changes into build service, triggers build
osc ci
